#!/usr/bin/env python
# -*- coding: utf-8 -*-

# xfce4-terminal-font.py -- programmatically change the font size of an
# xfce4-terminal.
#
# Copyright © 2013 Noah K. Tilton <noahktilton@gmail.com>
#
# License: GPLv2 or later.

# working with xfce4-terminal-0.6.2-1

if __name__ == "__main__":

    import sys

    PM = ["+", "-"]
    if len(sys.argv) != 2 or sys.argv[1] not in PM:
        sys.exit("Usage {0} {1}".format(sys.argv[0], "/".join(PM)))

    delta = int("{0}1".format(sys.argv[1]))

    import os
    try:
        from configparser import RawConfigParser  # python3
    except ImportError:
        from ConfigParser import RawConfigParser  # python2

    # read input file
    try:
        f = os.path.join(os.environ["XDG_CONFIG_HOME"], "xfce4", "terminal", "terminalrc")
    except KeyError:
        # XDG_CONFIG_HOME environment variable not defined
        f = os.path.join(os.environ["HOME"], ".config", "xfce4", "terminal", "terminalrc")

    c = RawConfigParser()
    c.optionxform = str # make keys case-sensitive
    c.read(f)
    font, size = c.get('Configuration', 'FontName').split()
    size = float(size) + delta
    c.set('Configuration', 'FontName', "{0} {1}".format(font, size))

    with open(f, 'w') as c_new:
        c.write(c_new)
