#!/usr/bin/env python
# -*- coding: utf-8 -*-

# xfce4-terminal-font.py -- programmatically change the font size of an
# xfce4-terminal.
#
# Copyright © 2013 Noah K. Tilton <noahktilton@gmail.com>
# Copyright © 2017 Edoardo Negri <edne@gmx.com>
#
# License: GPLv2 or later.

from sys import argv
import os
try:
    from configparser import RawConfigParser  # python3
except ImportError:
    from ConfigParser import RawConfigParser  # python2


if __name__ == '__main__':
    if len(argv) != 2 or argv[1] not in ['+', '-']:
        exit('Usage {} +/-'.format(argv[0]))

    delta = int('{}1'.format(argv[1]))

    try:
        config_root = os.environ['XDG_CONFIG_HOME']
    except KeyError:
        config_root = os.path.join(os.environ['HOME'], '.config')

    config_file = os.path.join(config_root, 'xfce4', 'terminal', 'terminalrc')

    config = RawConfigParser()
    config.optionxform = str  # make keys case-sensitive
    config.read(config_file)

    font, size = config.get('Configuration', 'FontName').split()

    new_size = float(size) + delta
    config.set('Configuration', 'FontName', '{} {}'.format(font, new_size))

    with open(config_file, 'w') as f:
        config.write(f)
